// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipCheaperTaskLibrary.Database;

namespace ShipCheaperTaskLibrary.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ShipCheaperTaskLibrary.Dbos.FavoriteMovieInfo", b =>
            {
                b.Property<string>("ImdbID")
                    .HasColumnType("TEXT");

                b.Property<string>("Genre")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<string>("Poster")
                    .HasColumnType("TEXT");

                b.Property<string>("Runtime")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.Property<string>("Writer")
                    .HasColumnType("TEXT");

                b.Property<string>("Year")
                    .HasColumnType("TEXT");

                b.HasKey("ImdbID");

                b.ToTable("FavoriteMovies");
            });
#pragma warning restore 612, 618
        }
    }
}